### ISSUE TITLE
Impossible to build mongoDB database

### ISSUE THREAD

**Issue by kalon33** [fnogatz/timetraveller#1]
Currently I have this error of JavaScript heap out of memory:
```
xxx@spiralo:/var/www/transports/timetraveller$ transportation positions stif | timetraveller-mongodb import Paris
[23:32:23.208] [LOG] Start import of GeoJSON
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0xef753c [node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
    v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node]
 6: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 7: 0xdbe39a079a7
undefined:1
<--- Last few GCs --->
^

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at Stream.<anonymous> (/usr/local/lib/node_modules/timetraveller-mongodb/bin/timetraveller-mongodb-import:44:22)
    at emitOne (events.js:96:13)
    at Stream.emit (events.js:188:7)
    at drain (/usr/local/lib/node_modules/timetraveller-mongodb/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/usr/local/lib/node_modules/timetraveller-mongodb/node_modules/through/index.js:45:5)
    at Stream.write (/usr/local/lib/node_modules/timetraveller-mongodb/node_modules/binary-split/index.js:32:16)
    at Stream.stream.write (/usr/local/lib/node_modules/timetraveller-mongodb/node_modules/through/index.js:26:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
```

How can I circumvent this?

**Comment by kalon33** [comment]
Is there any way to raise memory limit? I don't even reach half my computer memory (by far) but don't know how to adjust it

**Comment by fnogatz** [comment]
What GTFS data are you trying to import? If they are available online, it would be easier to find the bug ;)

I tried the [example](https://github.com/fnogatz/timetraveller/wiki/Example-Setup-for-GTFS) of using Windsor GTFS data again with node `v7.7.4` and the import worked as expected.

**Comment by kalon33** [comment]
@fnogatz I tried this one: https://opendata.stif.info/explore/dataset/offre-horaires-tc-gtfs-idf/files/f24cf9dbf6f80c28b8edfdd99ea16aad/download/ 

with latest node/npm but it seems it ran out of memory (as GTFS zip file is >50Mb, sometimes as high as 75Mb). Same thing with other GTFS files of ~20Mb size. Is this possible to set an higher limit? Some transportation networks in larger cities than Windsor have larger datasets. 

----- Mail original -----

De: "Falco Nogatz" <notifications@github.com> 
À: "fnogatz/timetraveller" <timetraveller@noreply.github.com> 
Cc: "Nicolas Derive" <kalon33@ubuntu.com>, "Author" <author@noreply.github.com> 
Envoyé: Jeudi 27 Juillet 2017 02:16:29 
Objet: Re: [fnogatz/timetraveller] Impossible to build mongoDB database (#1) 



What GTFS data are you trying to import? If they are available online, it would be easier to find the bug ;) 

I tried the example of using Windsor GTFS data again with node v7.7.4 and the import worked as expected.
